import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
//import fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display:"swap"
});

const spaceGroTask = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  display:"swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${spaceGroTask.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
